PROJ_HOME="$HOME/models/research"
PYTHONPATH=$PROJ_HOME python3 $PROJ_HOME/object_detection/dataset_tools/create_coco_tf_record.py \
   --train_image_dir=$HOME/coco2014/train2014 \
   --val_image_dir=$HOME/coco2014/val2014 \
   --test_image_dir=$HOME/coco2014/test2014 \
   --train_annotations_file=$HOME/coco2014/annotations/instances_train2014.json \
   --val_annotations_file=$HOME/coco2014/annotations/instances_val2014.json \
   --testdev_annotations_file=$HOME/coco2014/annotations/image_info_test2014.json \
   --output_dir=$HOME/tfr2014
