type: 'retinanet'
train:
    train_file_pattern: '$HOME/tfrecords/coco_train'
eval:
    eval_file_pattern: '$HOME/tfrecords/coco_val'
    val_json_file: '$HOME/cocodataset/annotations/instances_val2017.json'
