type: 'retinanet'
train:
    train_file_pattern: '/home/khaled/tfrecords/coco_train*'
eval:
    eval_file_pattern: '/home/khaled/tfrecords/coco_val*'
    val_json_file: '/home/khaled/cocodataset/annotations/instances_val2017.json'
