type: 'retinanet'
train:
    train_file_pattern: '$HOME/experiments/retinanet/train'
eval:
    eval_file_pattern: '$HOME/experiments/retinanet/eval'
    val_json_file: '$HOME/experiments/retinanet/eval-annotations'
