type: 'retinanet'
architecture:
    backbone: 'spinenet'
    multilevel_features: 'identity'
spinenet: 
    model_id: '49'
train:
    train_file_pattern: '/nodclouddata/mscoco/tfr2017/coco_train.*'
    batch_size: 8
    learning_rate:
        init_learning_rate: 0.04
eval:
    eval_file_pattern: '/nodclouddata/mscoco/tfr2017/coco_val.*'
    val_json_file: '/nodclouddata/mscoco/coco2017/annotations/instances_val2017.json'
    batch_size: 8
