type: 'retinanet'
architecture:
    backbone: 'spinenet'
    multilevel_features: 'identity'
spinenet: 
    model_id: 190
train:
    train_file_pattern: '/nodclouddata/mscoco/coco2017/tfr2017/coco_train.*'
    batch_size: 8
eval:
    eval_file_pattern: '/nodclouddata/mscoco/coco2017/tfr2017/coco_val.*'
    val_json_file: '/nodclouddata/mscoco/coco2017/annotations/instances_val2017.json'
    batch_size: 8
